disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
- type_name
- line_length
- large_tuple
- multiple_closures_with_trailing_closure

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
